// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(PostDbContext))]
    partial class PostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is a post made in a .net minimal web api",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
